[package]
name = "auto_script"
version = "0.1.0"
edition = "2021"

[dependencies]
clap_derive = "4.5.5"
clap = { version = "4.5.7", features = ["derive"] }
log = "0.4.21"
env_logger = "0.11.3"
humantime = "2.1.0"
chrono = "0.4.38"
termcolor = "1.4.1"
anyhow = "1.0.86"
